//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SmallToolKit.rc
//
#define IDGETPRIMERS                    3
#define ID_ASCCI                        4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SMALLTOOLKIT_DIALOG         102
#define IDD_PROPPAGE_DATA               106
#define IDD_PROPPAGE_Num                107
#define IDD_PROPPAGE_RADIX              108
#define IDD_PROPPAGE_NET                109
#define IDD_PROPPAGE_FSPLIT             110
#define IDD_PROPPAGE_CODE               111
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_ASCCI                131
#define IDD_DIALOG_PRIME                132
#define IDD_PROPPAGE_CHKSUM             133
#define IDD_WAIT_DIALOG                 137
#define IDC_EDIT_NUM1                   1000
#define IDC_CHECK_FROM                  1000
#define IDC_EDIT_NUM2                   1001
#define IDC_EDIT_FROM                   1001
#define IDC_EDIT_NUM3                   1002
#define IDC_CHECK_TO                    1002
#define IDC_EDIT_TO                     1003
#define IDC_RADIO_GCD                   1003
#define IDC_RADIO_LCM                   1004
#define IDC_EDIT_INPUT                  1004
#define IDC_RADIO_LIM                   1005
#define IDC_EDIT_OUTPUT                 1005
#define IDC_RADIO_MOD                   1006
#define IDC_EDIT_SIZE                   1006
#define IDC_RADIO_XOR                   1007
#define IDC_SLIDER1                     1007
#define IDC_RADIO_OR                    1008
#define IDC_BUTTON_FILE                 1008
#define IDC_EDIT_INPUT_NUM              1008
#define IDC_RADIO_AND                   1009
#define IDC_CHECK_RADIX                 1009
#define IDC_RADIO_ADD                   1010
#define IDC_EDIT_RADIX                  1010
#define IDC_RADIO_SUB                   1011
#define IDC_EDIT_OUTPUT_NUM             1011
#define IDC_EDIT_GROUP1                 1011
#define IDC_RADIO_MUL                   1012
#define IDC_CHECK_OUTPUT_RADIX          1012
#define IDC_EDIT_GROUP2                 1012
#define IDC_RADIO_DIV                   1013
#define IDC_EDIT_OUTPUT_RADIX           1013
#define IDC_EDIT_GROUP3                 1013
#define IDC_EDIT_KEY_VALUE              1013
#define IDC_RADIO_REV                   1014
#define IDC_EDIT_GROUP5                 1014
#define IDC_EDIT_GROUP4                 1015
#define IDC_EDIT_GROUP6                 1017
#define IDC_RADIO_CLIENT                1018
#define IDC_RADIO_SERVER                1019
#define IDC_EDIT_HOST                   1020
#define IDC_EDIT_PORT                   1021
#define IDC_RADIO_UDP                   1022
#define IDC_RADIO_TCP                   1023
#define IDC_RADIO_RAW                   1024
#define IDC_CHECK_HDRINCL               1025
#define IDC_CHECK_STRING                1026
#define IDC_EDIT_FILE_PATH              1029
#define IDC_BUTTON_GETFILES             1030
#define IDC_CHECK_SUFFIX                1031
#define IDC_EDIT_SUFFIX                 1032
#define IDC_RADIO_SIZE                  1034
#define IDC_RADIO_KERYVALUE             1035
#define IDC_RADIO_SPLIT                 1038
#define IDC_RADIO_COMBINE               1039
#define IDC_BUTTON_DSTFILENAME          1042
#define IDC_EDIT_DST_FILE               1043
#define IDC_LIST_FILE_LIST              1044
#define IDC_BUTTON_DELETE               1045
#define IDC_BUTTON_UP                   1046
#define IDC_BUTTON_DOWN                 1047
#define IDC_BUTTON_OPEN                 1048
#define IDC_LIST_FILE                   1054
#define IDC_CHECK_SELF                  1055
#define IDC_EDIT_SELF                   1056
#define ID_BUTTON_CALC                  1057
#define IDC_STATIC_TABLE                1059
#define IDC_EDIT_MAX_NUM                1060
#define IDC_COMBO_OPERATE               1063
#define IDC_EDIT_FILEPATH               1064
#define IDC_BUTTON_BROWSE               1066
#define IDC_EDIT_CRC16                  1067
#define IDC_EDIT_CRC_CCITT              1068
#define IDC_EDIT_CRC32                  1069
#define IDC_EDIT_CRC32C                 1070
#define IDC_EDIT_CRC_WIDTH              1071
#define IDC_EDIT_POLY                   1072
#define IDC_EDIT_INIT                   1074
#define IDC_EDIT_OUTXOR                 1075
#define IDC_CHECK_IN                    1076
#define IDC_CHECK_OUT                   1077
#define IDC_EDIT_CRC                    1078
#define IDC_PROGRESS                    1079
#define IDC_LIST_CHKSUM                 1080
#define IDC_STATIC_TEXT                 1081
#define IDC_CHECK_CUST                  1082
#define IDC_EDIT_DATA                   1083
#define IDC_RADIO_MATH                  1084
#define IDC_EDIT_MATH                   1085
#define IDC_EDIT_EXPR                   1086

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1087
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
